### PR TITLE
add demo for adding new fields in a repeatable at the top

### PR DESCRIPTION
**Pull request by nschoenholtz**
Demo for the functionality added by @jitendraharpalani58 in https://github.com/alleyinteractive/wordpress-fieldmanager/pull/247

### CODE REVIEW

**Comment by mboynes** [comment]
Should this be added _in addition_ to how it was setup previously?

**Comment by nschoenholtz** [comment]
I was thinking that before the change, it was extremely similar to `Repeating Standalone Text Field` above, but it certainly wouldn't take much argument to convince me to add a separate example instead.

**Comment by mboynes** [comment]
Yeah, I wonder why we have those two identical fields! I'm cool with this change as-is then. Can you just change the meta box title? then :horse:

**Comment by nschoenholtz** [comment]
Good call, thanks -- what do you think of, "Repeatable text fields with new items at the top"?

**Comment by mboynes** [comment]
I like it enough to merge it!

**Comment by nschoenholtz** [comment]
Haha thanks!

**Pull request merged**
